--- #YAML:1.0
name:                GD
version:             2.41
abstract:            Interface to Gd Graphics Library
license:             ~
author:              
    - Lincoln Stein (lstein@cshl.org)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Math::Trig:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
