---
abstract: 'Perl interface to the gd2 graphics library'
author:
  - 'Lincoln Stein <lincoln.stein@gmail.com>'
build_requires:
  ExtUtils::CBuilder: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GD
provides:
  GD:
    file: lib/GD.pm
    version: '2.56'
  GD::Group:
    file: lib/GD/Group.pm
    version: '1'
  GD::Polygon:
    file: lib/GD/Polygon.pm
  GD::Polyline:
    file: lib/GD/Polyline.pm
    version: '0.2'
  GD::Simple:
    file: lib/GD/Simple.pm
requires:
  Math::Trig: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '2.56'
x_repository:
  type: git
  url: git://github.com/lstein/Perl-GD.git
  web: https://github.com/lstein/Perl-GD
